---
title: Stichting Voelspriet
baseURL: http://www.stichtingvoelspriet.nl
theme: theme
googleAnalytics: UA-98368287-1
disableKinds:
- RSS
- sitemap
- taxonomy
- taxonomyTerm
params:
  subtitle: Beleef de wereld, ga mee op avontuur
  description: 'Stichting Voelspriet bedenkt, initieert en produceert avonturen. De
    inspiratie voor onze avonturen komt uit maatschappelijk thema''s zoals: natuur
    & milieu, duurzaamheid, cultuur en actuele onderwerpen. Vakinhoudelijke kennis
    en jaren ervaring als projectmanager worden In Stichting Voelspriet gecombineerd
    met creativiteit en een flinke dosis nieuwsgierigheid.'
  keywords: natuur, milieu, duurzaamheid, cultuur, actueel onderwerp, avontuur, educatie,
    interactief, kunst
  imageUrl: https://res.cloudinary.com/stichtingvoelspriet/image/upload/v1541276841/%v/%v.jpg
  thumbnailUrl: https://res.cloudinary.com/stichtingvoelspriet/image/upload/c_lfill,h_200,w_200/v1541276841/%v/%v.jpg
  scribble:
    '':
      name: Peuters natuurlijk!
      url: "/peuters-natuurlijk"
    peuters-natuurlijk:
      name: Stichting Voelspriet
      url: "/"
menu:
  '':
  - url: "#contact"
    name: Contact
    weight: 5
  - url: "#wie"
    name: Wie
    weight: 4
  - url: "#wat"
    name: Wat
    weight: 3
  - url: "#hoe"
    name: Hoe
    weight: 2
  - url: "#visie"
    name: Visie
    weight: 1
  external:
  - pre: "<i class='fab fa-facebook'></i>"
    url: https://www.facebook.com/stichtingvoelspriet
    name: facebook
    weight: 1
  peuters-natuurlijk:
  - url: "#contact"
    name: Contact
    weight: 8
  - url: "#zo-zag-dat-er-uit"
    name: Zo zag dat er uit
    weight: 7
  - url: "#doelstelling"
    name: Doelstelling
    weight: 6
  - url: "#referenties"
    name: Referenties
    weight: 5
  - url: "#wanneer"
    name: Wanneer
    weight: 4
  - url: "#wat"
    name: Wat
    weight: 3
  - url: "#waar"
    name: Waar
    weight: 2
  - url: "#peuters-natuurlijk"
    name: Peuters natuurlijk!
    weight: 1
