---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/peuters-natuurlijk
  label: Peuters natuurlijk!
  create: all
  match: "*.md"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*.md"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "*.md"
upload_dir: https://res.cloudinary.com/stichtingvoelspriet/image/upload/v1541276841
public_path: https://res.cloudinary.com/stichtingvoelspriet/image/upload/v1541276841
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.62.2
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.62.2
